controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

service_status:
    path: /service/status
    controller: App\Controller\ServiceStatusController::ping
    methods: GET

get_recipes:
    path: /api/recipe
    controller: App\Controller\RecipeController::getUserRecipes
    methods: GET

get_recipe:
    path: /api/recipe/{recipeid}
    controller: App\Controller\RecipeController::getRecipe
    methods: GET

scrape_recipe:
    path: /api/scrape
    controller: App\Controller\RecipeController::scrape

save_recipe:
    path: /api/recipe
    controller: App\Controller\RecipeController::saveNewRecipe
    methods: POST

delete_recipe:
    path: /api/recipe/{recipeid}
    controller: App\Controller\RecipeController::deleteRecipe
    methods: DELETE

menu:
    path: /api/menu
    controller: App\Controller\MenuController::getMenu
    methods: GET

save_menu:
    path: /api/menu/save
    controller: App\Controller\MenuController::saveMenu
    methods: POST

grocery_list:
    path: /api/grocerylist
    controller: App\Controller\GroceryListController::getGroceryList
    methods: GET

save_grocery_list:
    path: /api/grocerylist
    controller: App\Controller\GroceryListController::saveGroceryList
    methods: POST

signup:
    path: /api/signup
    controller: App\Controller\RegistrationController::signup
    methods: POST

api_login_check:
    path: /api/login_check
api_logout:
    path: /api/logout
    controller: App\Controller\AuthController::logout
    methods: POST

api_refresh_token:
    path:       /token/refresh
    methods: POST