controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

service_status:
    path: /service/status
    controller: App\Controller\ServiceStatusController::ping
    methods: GET

menu:
    path: /api/menu
    controller: App\Controller\MenuController::getMenu
    methods: GET

save_menu:
    path: /api/menu/save
    controller: App\Controller\MenuController::saveMenu
    methods: POST

grocery_list:
    path: /api/grocerylist
    controller: App\Controller\GroceryListController::getGroceryList
    methods: GET

save_grocery_list:
    path: /api/grocerylist
    controller: App\Controller\GroceryListController::saveGroceryList
    methods: POST

signup:
    path: /api/signup
    controller: App\Controller\RegistrationController::signup
    methods: POST

api_login_check:
    path: /api/login_check
api_logout:
    path: /api/logout

api_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh