name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get runner's public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist the runner IP
        run: |
          curl -sm 45 -H'Authorization: cpanel ${{ secrets.REMOTE_USER }}:${{ secrets.o2switch_API_TOKEN }}' \
          'https://${{ secrets.REMOTE_HOST }}:2083/execute/SshWhitelist/add?address=${{ steps.ip.outputs.ipv4 }}&port=22&direction=in'

      - name: deploy to VPS
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.PROD_REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"

      - name: Remove runner's IP from Whitelist
        if: always()
        run: |
            curl -sm 45 -H'Authorization: cpanel ${{ secrets.REMOTE_USER }}:${{ secrets.o2switch_API_TOKEN }}' \
            'https://${{ secrets.REMOTE_HOST }}:2083/execute/SshWhitelist/remove?address=${{ steps.ip.outputs.ipv4 }}&port=22&direction=out'